
- name: Install artifacts and restart service
  hosts: web-bucboot
  gather_facts: no
  serial: "{{ batch_size | default(10) }}"
  # deploy_type: "{{ type | default('snapshot')}}"
  max_fail_percentage: 100
  become: yes

  tasks:
    - name: "Inform about new version"
      debug:
        msg: "Going to install TD {{ total_insurance_version }} on cluster {{ cluster_name }} with spring profiles {{ spring_profiles_active }}"
      tags: debug

    - name: Copy local file {{ item }} to  /opt/tomcat/conf/{{ item | basename }}
      tags: copy_files
      copy: src={{ item }} dest=/opt/tomcat/conf/{{ item | basename }} owner=tomcat group=root mode=644
      with_items: "{{ local_files }}"

    - name: "Fetch artifact"
      debug:
        msg: "Going to install artifact from: {{ artifactory_snapshot_repo }}/org/bootcamp/total-insurance/1.0-SNAPSHOT/total-insurance-{{ total_insurance_version }}.war"
      tags: debug

    - name: Download WAR
      get_url: url="{{ artifactory_snapshot_repo }}/org/bootcamp/total-insurance/1.0-SNAPSHOT/total-insurance-{{ total_insurance_version }}.war" dest=/opt/tomcat/webapps/ROOT.war mode=0440 owner=tomcat url_username=bucboot url_password={{ bucboot_password }} force=yes

    - name: Activate spring profiles
      lineinfile: dest=/opt/tomcat/conf/catalina.properties regexp='^spring.profiles.active=' line="spring.profiles.active={{ spring_profiles_active }}"

    - name: Restart Tomcat
      service: name=tomcat state=restarted
      tags:
        - restart
        - tomcat

    - name: Wait for Tomcat8 to kick in
      wait_for: port=8080 delay=2 timeout=60
      tags:
        - healthcheck
        - tomcat

    - name: Restart Nginx
      service: name=nginx state=restarted
      tags:
        - restart
        - nginx

    - name: Wait for Nginx to kick in
      wait_for: port=80 delay=2 timeout=60
      tags:
        - healthcheck
        - nginx


