
- name: Install artifacts and restart service
  hosts: web-bucboot
  gather_facts: no
  max_fail_percentage: 100
  become: yes
  vars:
    db_type: "{{ db | default('jsondb') }}"
    deploy_type: "{{ type | default('snapshot') }}"

  tasks:
    - name: "Inform about new version"
      debug:
        msg: "Going to install TD {{ total_insurance_version }} on cluster {{ cluster_name }} with spring profiles {{ db_type }}"
      tags: debug

    - name: Copy local file {{ item }} to  /opt/tomcat/conf/{{ item | basename }}
      tags: copy_files
      copy: src={{ item }} dest=/opt/tomcat/conf/{{ item | basename }} owner=tomcat group=root mode=644
      with_items: "{{ local_files }}"

    - name: "Fetch artifact snapshot"
      debug:
        msg: "Going to install artifact from: {{ artifactory_snapshot_repo }}/org/bootcamp/{{artifact_name}}/1.0-SNAPSHOT/{{artifact_name}}e-{{ total_insurance_version }}.war"
      tags: debug
      when: deploy_type == "snapshot"

    - name: "Fetch artifact release"
      debug:
        msg: "Going to install artifact from: {{ artifactory_release_repo }}/org/bootcamp/{{artifact_name}}/1.0/{{artifact_name}}-{{ total_insurance_version }}.war"
      tags: debug
      when: deploy_type == "release"

    - name: Download WAR snapshot war
      get_url: url="{{ artifactory_snapshot_repo }}/org/bootcamp/{{artifact_name}}/1.0-SNAPSHOT/{{artifact_name}}-{{ total_insurance_version }}.war" dest=/opt/tomcat/webapps/ROOT.war mode=0440 owner=tomcat url_username=bucboot url_password={{ bucboot_password }} force=yes
      when: deploy_type == "snapshot"

    - name: Download WAR release war
      get_url: url="{{ artifactory_release_repo }}/org/bootcamp/{{artifact_name}}/1.0/{{artifact_name}}-{{ total_insurance_version }}.war" dest=/opt/tomcat/webapps/ROOT.war mode=0440 owner=tomcat url_username=bucboot url_password={{ bucboot_password }} force=yes
      when: deploy_type == "release"

    - name: Activate spring profiles
      lineinfile: dest=/opt/tomcat/conf/catalina.properties regexp='^spring.profiles.active=' line="spring.profiles.active={{ db_type }}"

    - name: Create env file
      file: path=/opt/tomcat/bin/setenv.sh owner=tomcat mode="u=rwx,g=r,o=r" state=touch

    - name: Activate db_type
      lineinfile: dest=/opt/tomcat/bin/setenv.sh regexp='-Dfilepath=' line="CATALINA_OPTS+=\" -Dfilepath={{ file_path[db_type] }}\"" mode=0740 owner=tomcat

    - name: Restart Tomcat
      service: name=tomcat state=restarted
      tags:
        - restart
        - tomcat

    - name: Wait for Tomcat8 to kick in
      wait_for: port=8080 delay=2 timeout=60
      tags:
        - healthcheck
        - tomcat

    - name: Restart Nginx
      service: name=nginx state=restarted
      tags:
        - restart
        - nginx

    - name: Wait for Nginx to kick in
      wait_for: port=80 delay=2 timeout=60
      tags:
        - healthcheck
        - nginx


